### ISSUE TITLE
Weird formatting of web page

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#512]
Went into the web interface and it looked like this: 
<img width="1440" alt="Screenshot 2021-06-17 at 08 41 27" src="https://user-images.githubusercontent.com/35953392/122346123-e74b5180-cf48-11eb-9203-62d184fae89d.png">
Tried clearing cache, didn't help. Rebuilt, didn't help. Removed everything and rebuilt, didn't help either. 

@pericsson had apparently experienced the same thing and it was resolved by clicking the dark mode and reloading the page.

**Comment by pericsson** [comment]
The developer console, in inspect for the page, showed this error: 
```
GEThttp://localhost:5000/static/css/dds_auto.css
[HTTP/1.0 404 NOT FOUND 32ms]
```

**Comment by ewels** [comment]
The formatting in the screenshot is due to a missing CSS file. So it's basically no formatting at all.

The error you see in the console seems to point to the `dds_auto.css` file not being generated / present. This makes sense that the toggle will fix it, as as soon as you start using the toggle the light or dark CSS style sheets are used directly. So it's only possible to use the auto CSS file if you have not yet touched the toggle (clear cookies to start fresh).

However - I've now tried on two computers with complete docker wipes and in Chrome, Safari and Firefox (with cleared caches), and am unable to replicate this..

**Comment by ewels** [comment]
Could you please see if the local file `dds_web/static/css/dds_auto.css` exists for you after running `docker compose up`?

**Comment by inaod568** [comment]
I haven't experienced this again, will close this issue for now. Feel free to open again if needed.
