### ISSUE TITLE
Check if timestamp timezone bug in token and if so fix

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#789]

**Comment by MatthiasZepper** [comment]
After the ongoing refactoring of the token endpoints are completed, we should test if changing the timezone of the Docker containers has unwanted side-effects in terms of token validity and lifetime. 

Since we create from and check against the `utils.current_time()` this shouldn't be the case:

https://github.com/ScilifelabDataCentre/dds_web/blob/1083347d3eecd404645ad58c6db2913c2411b6bf/dds_web/api/user.py#L92

https://github.com/ScilifelabDataCentre/dds_web/blob/1083347d3eecd404645ad58c6db2913c2411b6bf/dds_web/security/auth.py#L79-L82

But we use the `.timestamp()` and `.fromtimestamp()` functions to de-serialize and serialize the datetime from and to JSON, which looses the timezone information contained into the datetime object.  

Therefore, I used the isodate package that [Microsoft engineers recommend when using the Azure SDK for Python](https://github.com/ScilifelabDataCentre/dds_web/blob/1083347d3eecd404645ad58c6db2913c2411b6bf/dds_web/) in my draft pull requests #790 and [227](https://github.com/ScilifelabDataCentre/dds_cli/pull/227).
