### ISSUE TITLE
Test on windows too

### ISSUE THREAD

**Issue by aanil** [ScilifelabDataCentre/dds_web#846]
Reminder to test if the CLI works on Windows. A lot of our users work on Windows.

**Comment by inaod568** [comment]
Ahh damn windows. 😫

**Comment by inaod568** [comment]
I don't have access to Windows, do any of you? @alneberg @aanil @talavis @MatthiasZepper @worukan

**Comment by MatthiasZepper** [comment]
Not really, but [one can download virtual machines with WIndows from Microsoft for development and test purposes for free](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/). This is what I used for testing the Rich output for the symbols back then. 

I have since however updated my private laptop and no Virtual Machine Host anymore (Could install it of course again).

**Comment by alneberg** [comment]
I actually have a laptop with windows so I could try it out there as well. I guess debugging more tricky issues might be worse though.

**Comment by inaod568** [comment]
@MatthiasZepper During this week

**Comment by inaod568** [comment]
Need more tests on windows, not via a virtual machine.
