### ISSUE TITLE
Rethink format of keys in db? (change from bytes - yes or no)

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#866]
At the moment all keys are stored as bytes in the database which makes it very difficult to display the table contents with `mysql` in the terminal. Either we need to figure out how to display this in a way that doesn't completely mess up the terminal output or we need to change to either hex or something else more readable. 

Install Beekeeper for now. A lot cleaner output.

**Comment by MatthiasZepper** [comment]
In the meantime, you might want to try [Beekeeper Studio](https://www.beekeeperstudio.io) instead of the CLI? 
I already persuaded Johannes and Anand...

**Comment by inaod568** [comment]
@MatthiasZepper 
Thaaank yoou! This helped a lot!

**Comment by worukan** [comment]
I want to share how the keys are ended up stored in bytes in the db. As I can search from online, there is no fact that opposes doing it. Moreover, I have read that it is more natural to keep it in its original type as you won't need to do extra conversions when passing it to the functions. Why do we need hex? Because we can't just stream plain bytes over the Internet. It is still not for human readability as far as I know.

**Comment by inaod568** [comment]
Moving to Jira.
